import 'eud_field_manifest.dart';

/// Audited classic DAT projection. Player supply limits are runtime state, not DAT.
abstract final class EudDatLayout {
  static const revision = 'classic-dat-v1-pyms-bfc5d3a-eudplib-0.80.6';
  static const assets = <String, int>{
    "arr\\units.dat": 19876,
    "arr\\weapons.dat": 5460,
    "arr\\flingy.dat": 3135,
    "arr\\upgrades.dat": 1281,
    "arr\\techdata.dat": 836,
    "arr\\sprites.dat": 3229,
    "arr\\images.dat": 37962,
  };
  static const counts = <String, int>{
    'unit.groundWeapon': 228,
    'unit.airWeapon': 228,
    'unit.flingy': 228,
    'unit.seekRange': 228,
    'unit.sightRange': 228,
    'unit.sizeType': 228,
    'unit.baseProperty': 228,
    'unit.portrait': 228,
    'unit.readySound': 106,
    'unit.whatSoundStart': 228,
    'unit.whatSoundEnd': 228,
    'unit.pissedSoundStart': 106,
    'unit.pissedSoundEnd': 106,
    'unit.yesSoundStart': 106,
    'unit.yesSoundEnd': 106,
    'weapon.targetFlags': 130,
    'weapon.cooldown': 130,
    'weapon.damageFactor': 130,
    'weapon.attackAngle': 130,
    'weapon.launchSpin': 130,
    'weapon.removeAfter': 130,
    'weapon.splashInnerRadius': 130,
    'weapon.splashMiddleRadius': 130,
    'weapon.splashOuterRadius': 130,
    'weapon.behavior': 130,
    'weapon.explosionType': 130,
    'weapon.flingy': 130,
    'flingy.topSpeed': 209,
    'flingy.acceleration': 209,
    'flingy.haltDistance': 209,
    'flingy.turnSpeed': 209,
    'flingy.movementControl': 209,
    'flingy.sprite': 209,
    'upgrade.mineralCostBase': 61,
    'upgrade.mineralCostFactor': 61,
    'upgrade.gasCostBase': 61,
    'upgrade.gasCostFactor': 61,
    'upgrade.timeCostBase': 61,
    'upgrade.timeCostFactor': 61,
    'upgrade.maxLevel': 61,
    'upgrade.race': 61,
    'tech.race': 44,
    'tech.mineralCost': 44,
    'tech.gasCost': 44,
    'tech.timeCost': 44,
    'tech.energyCost': 44,
    'sprite.image': 517,
    'sprite.isVisible': 517,
    'image.isTurnable': 999,
    'image.isClickable': 999,
    'image.useFullIscript': 999,
    'image.drawIfCloaked': 999,
    'image.drawingFunction': 999,
    'unit.hasShield': 228,
    'unit.maxShield': 228,
    'weapon.minRange': 130,
    'weapon.maxRange': 130,
    'weapon.damageType': 130,
    'unit.subunit1': 228,
    'unit.subunit2': 228,
    'unit.construction_animation': 228,
  };
  static const widths = <String, int>{
    'unit.groundWeapon': 1,
    'unit.airWeapon': 1,
    'unit.flingy': 1,
    'unit.seekRange': 1,
    'unit.sightRange': 1,
    'unit.sizeType': 1,
    'unit.baseProperty': 4,
    'unit.portrait': 2,
    'unit.readySound': 2,
    'unit.whatSoundStart': 2,
    'unit.whatSoundEnd': 2,
    'unit.pissedSoundStart': 2,
    'unit.pissedSoundEnd': 2,
    'unit.yesSoundStart': 2,
    'unit.yesSoundEnd': 2,
    'weapon.targetFlags': 2,
    'weapon.cooldown': 1,
    'weapon.damageFactor': 1,
    'weapon.attackAngle': 1,
    'weapon.launchSpin': 1,
    'weapon.removeAfter': 1,
    'weapon.splashInnerRadius': 2,
    'weapon.splashMiddleRadius': 2,
    'weapon.splashOuterRadius': 2,
    'weapon.behavior': 1,
    'weapon.explosionType': 1,
    'weapon.flingy': 4,
    'flingy.topSpeed': 4,
    'flingy.acceleration': 2,
    'flingy.haltDistance': 4,
    'flingy.turnSpeed': 1,
    'flingy.movementControl': 1,
    'flingy.sprite': 2,
    'upgrade.mineralCostBase': 2,
    'upgrade.mineralCostFactor': 2,
    'upgrade.gasCostBase': 2,
    'upgrade.gasCostFactor': 2,
    'upgrade.timeCostBase': 2,
    'upgrade.timeCostFactor': 2,
    'upgrade.maxLevel': 1,
    'upgrade.race': 1,
    'tech.race': 1,
    'tech.mineralCost': 2,
    'tech.gasCost': 2,
    'tech.timeCost': 2,
    'tech.energyCost': 2,
    'sprite.image': 2,
    'sprite.isVisible': 1,
    'image.isTurnable': 1,
    'image.isClickable': 1,
    'image.useFullIscript': 1,
    'image.drawIfCloaked': 1,
    'image.drawingFunction': 1,
    'unit.hasShield': 1,
    'unit.maxShield': 2,
    'weapon.minRange': 4,
    'weapon.maxRange': 4,
    'weapon.damageType': 1,
    'unit.subunit1': 2,
    'unit.subunit2': 2,
    'unit.construction_animation': 4,
  };
  static const enumValues = <String, Map<int, String>>{
    'unit.sizeType': {0: 'Independent', 1: 'Small', 2: 'Medium', 3: 'Large'},
    'weapon.behavior': {
      0: 'Fly_DoNotFollowTarget',
      1: 'Fly_FollowTarget',
      2: 'AppearOnTargetUnit',
      3: 'PersistOnTargetSite',
      4: 'AppearOnTargetSite',
      5: 'AppearOnAttacker',
      6: 'AttackAndSelfDestruct',
      7: 'Bounce',
      8: 'AttackNearbyArea',
      9: 'GoToMaxRange',
    },
    'weapon.explosionType': {
      0: 'None',
      1: 'NormalHit',
      2: 'SplashRadial',
      3: 'SplashEnemy',
      4: 'Lockdown',
      5: 'NuclearMissile',
      6: 'Parasite',
      7: 'Broodlings',
      8: 'EmpShockwave',
      9: 'Irradiate',
      10: 'Ensnare',
      11: 'Plague',
      12: 'StasisField',
      13: 'DarkSwarm',
      14: 'Consume',
      15: 'YamatoGun',
      16: 'Restoration',
      17: 'DisruptionWeb',
      18: 'CorrosiveAcid',
      19: 'MindControl',
      20: 'Feedback',
      21: 'OpticalFlare',
      22: 'Maelstrom',
      24: 'SplashAir',
    },
    'flingy.movementControl': {
      0: 'FlingyDat',
      1: 'PartiallyMobile_Weapon',
      2: 'IscriptBin',
    },
    'upgrade.race': {0: 'Zerg', 1: 'Terran', 2: 'Protoss', 3: 'All'},
    'tech.race': {0: 'Zerg', 1: 'Terran', 2: 'Protoss', 3: 'All'},
    'image.drawingFunction': {
      0: 'Normal',
      1: 'NormalNoHallucination',
      2: 'NonVisionCloaking',
      3: 'NonVisionCloaked',
      4: 'NonVisionDecloaking',
      5: 'VisionCloaking',
      6: 'VisionCloaked',
      7: 'VisionDecloaking',
      8: 'EMPShockwave',
      9: 'UseRemapping',
      10: 'Shadow',
      12: 'WarpTexture',
      13: 'SelectionCircle',
      14: 'PlayerColorOverride',
      15: 'HideGFX_ShowSizeRect',
      16: 'Hallucination',
      17: 'WarpFlash',
    },
    'weapon.damageType': {
      0: 'Independent',
      1: 'Explosive',
      2: 'Concussive',
      3: 'Normal',
      4: 'IgnoreArmor',
    },
  };
  static const memory = <String, ({int address, int stride, int count})>{
    'unit.groundWeapon': (address: 0x6636b8, stride: 1, count: 228),
    'unit.airWeapon': (address: 0x6616e0, stride: 1, count: 228),
    'unit.flingy': (address: 0x6644f8, stride: 1, count: 228),
    'unit.seekRange': (address: 0x662db8, stride: 1, count: 228),
    'unit.sightRange': (address: 0x663238, stride: 1, count: 228),
    'unit.sizeType': (address: 0x662180, stride: 1, count: 228),
    'unit.baseProperty': (address: 0x664080, stride: 4, count: 228),
    'unit.portrait': (address: 0x662f88, stride: 2, count: 228),
    'unit.readySound': (address: 0x661fc0, stride: 2, count: 106),
    'unit.whatSoundStart': (address: 0x65ffb0, stride: 2, count: 228),
    'unit.whatSoundEnd': (address: 0x662bf0, stride: 2, count: 228),
    'unit.pissedSoundStart': (address: 0x663b38, stride: 2, count: 106),
    'unit.pissedSoundEnd': (address: 0x661ee8, stride: 2, count: 106),
    'unit.yesSoundStart': (address: 0x663c10, stride: 2, count: 106),
    'unit.yesSoundEnd': (address: 0x661440, stride: 2, count: 106),
    'weapon.targetFlags': (address: 0x657998, stride: 2, count: 130),
    'weapon.cooldown': (address: 0x656fb8, stride: 1, count: 130),
    'weapon.damageFactor': (address: 0x6564e0, stride: 1, count: 130),
    'weapon.attackAngle': (address: 0x656990, stride: 1, count: 130),
    'weapon.launchSpin': (address: 0x657888, stride: 1, count: 130),
    'weapon.removeAfter': (address: 0x657040, stride: 1, count: 130),
    'weapon.splashInnerRadius': (address: 0x656888, stride: 2, count: 130),
    'weapon.splashMiddleRadius': (address: 0x6570c8, stride: 2, count: 130),
    'weapon.splashOuterRadius': (address: 0x657780, stride: 2, count: 130),
    'weapon.behavior': (address: 0x656670, stride: 1, count: 130),
    'weapon.explosionType': (address: 0x6566f8, stride: 1, count: 130),
    'weapon.flingy': (address: 0x656ca8, stride: 4, count: 130),
    'flingy.topSpeed': (address: 0x6c9ef8, stride: 4, count: 209),
    'flingy.acceleration': (address: 0x6c9c78, stride: 2, count: 209),
    'flingy.haltDistance': (address: 0x6c9930, stride: 4, count: 209),
    'flingy.turnSpeed': (address: 0x6c9e20, stride: 1, count: 209),
    'flingy.movementControl': (address: 0x6c9858, stride: 1, count: 209),
    'flingy.sprite': (address: 0x6ca318, stride: 2, count: 209),
    'upgrade.mineralCostBase': (address: 0x655740, stride: 2, count: 61),
    'upgrade.mineralCostFactor': (address: 0x6559c0, stride: 2, count: 61),
    'upgrade.gasCostBase': (address: 0x655840, stride: 2, count: 61),
    'upgrade.gasCostFactor': (address: 0x6557c0, stride: 2, count: 61),
    'upgrade.timeCostBase': (address: 0x655b80, stride: 2, count: 61),
    'upgrade.timeCostFactor': (address: 0x655940, stride: 2, count: 61),
    'upgrade.maxLevel': (address: 0x655700, stride: 1, count: 61),
    'upgrade.race': (address: 0x655bfc, stride: 1, count: 61),
    'tech.race': (address: 0x656488, stride: 1, count: 44),
    'tech.mineralCost': (address: 0x656248, stride: 2, count: 44),
    'tech.gasCost': (address: 0x6561f0, stride: 2, count: 44),
    'tech.timeCost': (address: 0x6563d8, stride: 2, count: 44),
    'tech.energyCost': (address: 0x656380, stride: 2, count: 44),
    'player.zergControlMax': (address: 0x5821a4, stride: 4, count: 8),
    'player.terranSupplyMax': (address: 0x582234, stride: 4, count: 8),
    'player.protossPsiMax': (address: 0x5822c4, stride: 4, count: 8),
    'sprite.image': (address: 0x666160, stride: 2, count: 517),
    'sprite.isVisible': (address: 0x665c48, stride: 1, count: 517),
    'image.isTurnable': (address: 0x66e860, stride: 1, count: 999),
    'image.isClickable': (address: 0x66c150, stride: 1, count: 999),
    'image.useFullIscript': (address: 0x66d4d8, stride: 1, count: 999),
    'image.drawIfCloaked': (address: 0x667718, stride: 1, count: 999),
    'image.drawingFunction': (address: 0x669e28, stride: 1, count: 999),
    'unit.hasShield': (address: 0x6647b0, stride: 1, count: 228),
    'unit.maxShield': (address: 0x660e00, stride: 2, count: 228),
    'weapon.minRange': (address: 0x656a18, stride: 4, count: 130),
    'weapon.maxRange': (address: 0x657470, stride: 4, count: 130),
    'weapon.damageType': (address: 0x657258, stride: 1, count: 130),
  };
  static Object? value(String key, int raw) {
    final field = EudFieldManifest.find(key);
    return switch (field?.type) {
      EudValueType.boolean =>
        raw == 0
            ? false
            : raw == 1
            ? true
            : null,
      EudValueType.enumeration => enumValues[key]?[raw],
      EudValueType.unsignedInteger => raw,
      _ => null,
    };
  }
}
