// Default ID labels verified against BWAPI WeaponType/UpgradeType/TechType.cpp.
// https://github.com/bwapi/bwapi/tree/main/bwapi/BWAPILIB/Source
// BWAPI is LGPL-3.0 licensed; see docs/licenses/BWAPI.txt.
// Empty names represent unnamed slots; callers retain the kind and numeric ID.
const defaultWeaponNames = <String>[
  'Gauss Rifle',
  'Gauss Rifle Jim Raynor',
  'C 10 Canister Rifle',
  'C 10 Canister Rifle Sarah Kerrigan',
  'Fragmentation Grenade',
  'Fragmentation Grenade Jim Raynor',
  'Spider Mines',
  'Twin Autocannons',
  'Hellfire Missile Pack',
  'Twin Autocannons Alan Schezar',
  'Hellfire Missile Pack Alan Schezar',
  'Arclite Cannon',
  'Arclite Cannon Edmund Duke',
  'Fusion Cutter',
  '',
  'Gemini Missiles',
  'Burst Lasers',
  'Gemini Missiles Tom Kazansky',
  'Burst Lasers Tom Kazansky',
  'ATS Laser Battery',
  'ATA Laser Battery',
  'ATS Laser Battery Hero',
  'ATA Laser Battery Hero',
  'ATS Laser Battery Hyperion',
  'ATA Laser Battery Hyperion',
  'Flame Thrower',
  'Flame Thrower Gui Montag',
  'Arclite Shock Cannon',
  'Arclite Shock Cannon Edmund Duke',
  'Longbolt Missile',
  'Yamato Gun',
  'Nuclear Strike',
  'Lockdown',
  'EMP Shockwave',
  'Irradiate',
  'Claws',
  'Claws Devouring One',
  'Claws Infested Kerrigan',
  'Needle Spines',
  'Needle Spines Hunter Killer',
  'Kaiser Blades',
  'Kaiser Blades Torrasque',
  'Toxic Spores',
  'Spines',
  '',
  '',
  'Acid Spore',
  'Acid Spore Kukulza',
  'Glave Wurm',
  'Glave Wurm Kukulza',
  '',
  '',
  'Seeker Spores',
  'Subterranean Tentacle',
  'Suicide Infested Terran',
  'Suicide Scourge',
  'Parasite',
  'Spawn Broodlings',
  'Ensnare',
  'Dark Swarm',
  'Plague',
  'Consume',
  'Particle Beam',
  '',
  'Psi Blades',
  'Psi Blades Fenix',
  'Phase Disruptor',
  'Phase Disruptor Fenix',
  '',
  'Psi Assault',
  'Psionic Shockwave',
  'Psionic Shockwave TZ Archon',
  '',
  'Dual Photon Blasters',
  'Anti Matter Missiles',
  'Dual Photon Blasters Mojo',
  'Anti Matter Missiles Mojo',
  'Phase Disruptor Cannon',
  'Phase Disruptor Cannon Danimoth',
  'Pulse Cannon',
  'STS Photon Cannon',
  'STA Photon Cannon',
  'Scarab',
  'Stasis Field',
  'Psionic Storm',
  'Warp Blades Zeratul',
  'Warp Blades Hero',
  '',
  '',
  '',
  '',
  '',
  'Platform Laser Battery',
  'Independant Laser Battery',
  '',
  '',
  'Twin Autocannons Floor Trap',
  'Hellfire Missile Pack Wall Trap',
  'Flame Thrower Wall Trap',
  'Hellfire Missile Pack Floor Trap',
  'Neutron Flare',
  'Disruption Web',
  'Restoration',
  'Halo Rockets',
  'Corrosive Acid',
  'Mind Control',
  'Feedback',
  'Optical Flare',
  'Maelstrom',
  'Subterranean Spines',
  '',
  'Warp Blades',
  'C 10 Canister Rifle Samir Duran',
  'C 10 Canister Rifle Infested Duran',
  'Dual Photon Blasters Artanis',
  'Anti Matter Missiles Artanis',
  'C 10 Canister Rifle Alexei Stukov',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
];

const defaultUpgradeNames = <String>[
  'Terran Infantry Armor',
  'Terran Vehicle Plating',
  'Terran Ship Plating',
  'Zerg Carapace',
  'Zerg Flyer Carapace',
  'Protoss Ground Armor',
  'Protoss Air Armor',
  'Terran Infantry Weapons',
  'Terran Vehicle Weapons',
  'Terran Ship Weapons',
  'Zerg Melee Attacks',
  'Zerg Missile Attacks',
  'Zerg Flyer Attacks',
  'Protoss Ground Weapons',
  'Protoss Air Weapons',
  'Protoss Plasma Shields',
  'U 238 Shells',
  'Ion Thrusters',
  '',
  'Titan Reactor',
  'Ocular Implants',
  'Moebius Reactor',
  'Apollo Reactor',
  'Colossus Reactor',
  'Ventral Sacs',
  'Antennae',
  'Pneumatized Carapace',
  'Metabolic Boost',
  'Adrenal Glands',
  'Muscular Augments',
  'Grooved Spines',
  'Gamete Meiosis',
  'Metasynaptic Node',
  'Singularity Charge',
  'Leg Enhancements',
  'Scarab Damage',
  'Reaver Capacity',
  'Gravitic Drive',
  'Sensor Array',
  'Gravitic Boosters',
  'Khaydarin Amulet',
  'Apial Sensors',
  'Gravitic Thrusters',
  'Carrier Capacity',
  'Khaydarin Core',
  '',
  '',
  'Argus Jewel',
  '',
  'Argus Talisman',
  '',
  'Caduceus Reactor',
  'Chitinous Plating',
  'Anabolic Synthesis',
  'Charon Boosters',
  '',
  '',
  '',
  '',
  '',
  'Upgrade 60',
];

const defaultTechNames = <String>[
  'Stim Packs',
  'Lockdown',
  'EMP Shockwave',
  'Spider Mines',
  'Scanner Sweep',
  'Tank Siege Mode',
  'Defensive Matrix',
  'Irradiate',
  'Yamato Gun',
  'Cloaking Field',
  'Personnel Cloaking',
  'Burrowing',
  'Infestation',
  'Spawn Broodlings',
  'Dark Swarm',
  'Plague',
  'Consume',
  'Ensnare',
  'Parasite',
  'Psionic Storm',
  'Hallucination',
  'Recall',
  'Stasis Field',
  'Archon Warp',
  'Restoration',
  'Disruption Web',
  '',
  'Mind Control',
  'Dark Archon Meld',
  'Feedback',
  'Optical Flare',
  'Maelstrom',
  'Lurker Aspect',
  '',
  'Healing',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
];

String settingsName(
  String kind,
  int id,
  List<String> defaults, {
  String? custom,
}) {
  final name = custom != null && custom.trim().isNotEmpty
      ? custom
      : id >= 0 && id < defaults.length
      ? defaults[id]
      : '';
  return name.isEmpty ? '$kind #$id' : '$name ($kind #$id)';
}
