import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:starcraft_map_editor/application/eud/eud_build_configuration.dart';
import 'package:starcraft_map_editor/application/ports/eud_build_file_gateway.dart';
import 'package:starcraft_map_editor/infrastructure/filesystem/local_eud_build_file_gateway.dart';

void main() {
  group('LocalEudBuildFileGateway', () {
    late Directory root;
    late Directory sourceRoot;
    late Directory outputRoot;
    late File baseMap;
    late File entrySource;
    late LocalEudBuildFileGateway gateway;

    setUp(() async {
      root = await Directory.systemTemp.createTemp('eud-build-files-한글-');
      sourceRoot = await Directory(
        '${root.path}${Platform.pathSeparator}EUD Source',
      ).create();
      outputRoot = await Directory(
        '${root.path}${Platform.pathSeparator}Build Output',
      ).create();
      baseMap = await File(
        '${root.path}${Platform.pathSeparator}Base Map.scx',
      ).writeAsBytes([1, 2, 3], flush: true);
      entrySource = await File(
        '${sourceRoot.path}${Platform.pathSeparator}main.eps',
      ).writeAsString('function onPluginStart() {}', flush: true);
      gateway = LocalEudBuildFileGateway();
    });

    tearDown(() async {
      if (await root.exists()) {
        await root.delete(recursive: true);
      }
    });

    test(
      'writes a one-shot UTF-8 eds manifest in an owned workspace',
      () async {
        final configuration = _configuration(
          baseMap: baseMap,
          sourceRoot: sourceRoot,
          entrySource: entrySource,
          outputRoot: outputRoot,
          compilerOptions: const {
            'debug': '',
            'shufflePayload': 'true',
            'decodeUnitName': 'UTF-8',
          },
        );

        await gateway.validateInputs(configuration);
        final workspace = await gateway.createWorkspace(configuration);
        final settings = await File(workspace.settingsFilePath).readAsString();

        expect(
          workspace.directoryPath,
          startsWith(
            '${outputRoot.path}${Platform.pathSeparator}'
            '.starcraft_map_editor_eud_',
          ),
        );
        expect(settings, startsWith(':: Generated by StarCraft Map Editor.'));
        expect(settings, contains('[main]\r\n'));
        expect(settings, contains('input: ${baseMap.path}\r\n'));
        expect(
          settings,
          contains('output: ${workspace.temporaryOutputMapPath}\r\n'),
        );
        expect(
          settings.indexOf('decodeUnitName: UTF-8'),
          lessThan(settings.indexOf('shufflePayload: true')),
        );
        expect(settings, contains('\r\ndebug\r\n'));
        expect(settings, contains('[${entrySource.path}]\r\n'));

        await gateway.cleanup(workspace);
        expect(await Directory(workspace.directoryPath).exists(), isFalse);
      },
    );

    test(
      'promotes a verified temporary output without touching the base map',
      () async {
        final configuration = _configuration(
          baseMap: baseMap,
          sourceRoot: sourceRoot,
          entrySource: entrySource,
          outputRoot: outputRoot,
        );
        final workspace = await gateway.createWorkspace(configuration);
        await File(
          workspace.temporaryOutputMapPath,
        ).writeAsBytes([9, 8, 7], flush: true);

        final result = await gateway.promote(
          workspace: workspace,
          destinationPath: configuration.outputMapPath,
          replaceExisting: false,
        );

        expect(result.backupPath, isNull);
        expect(await File(configuration.outputMapPath).readAsBytes(), [
          9,
          8,
          7,
        ]);
        expect(await baseMap.readAsBytes(), [1, 2, 3]);

        await gateway.cleanup(workspace);
      },
    );

    test('backs up a confirmed existing output before promotion', () async {
      final configuration = _configuration(
        baseMap: baseMap,
        sourceRoot: sourceRoot,
        entrySource: entrySource,
        outputRoot: outputRoot,
      );
      await File(
        configuration.outputMapPath,
      ).writeAsBytes([4, 5, 6], flush: true);
      final workspace = await gateway.createWorkspace(configuration);
      await File(
        workspace.temporaryOutputMapPath,
      ).writeAsBytes([9, 8, 7], flush: true);

      final result = await gateway.promote(
        workspace: workspace,
        destinationPath: configuration.outputMapPath,
        replaceExisting: true,
      );

      expect(result.backupPath, isNotNull);
      expect(await File(result.backupPath!).readAsBytes(), [4, 5, 6]);
      expect(await File(configuration.outputMapPath).readAsBytes(), [9, 8, 7]);

      await gateway.cleanup(workspace);
      expect(await File(result.backupPath!).exists(), isTrue);
    });

    test('restores the existing output when promotion fails', () async {
      var moveCount = 0;
      gateway = LocalEudBuildFileGateway(
        fileMover: (source, destinationPath) async {
          moveCount++;
          if (moveCount == 2) {
            throw FileSystemException(
              'simulated promotion failure',
              destinationPath,
            );
          }
          await source.rename(destinationPath);
        },
      );
      final configuration = _configuration(
        baseMap: baseMap,
        sourceRoot: sourceRoot,
        entrySource: entrySource,
        outputRoot: outputRoot,
      );
      await File(
        configuration.outputMapPath,
      ).writeAsBytes([4, 5, 6], flush: true);
      final workspace = await gateway.createWorkspace(configuration);
      await File(
        workspace.temporaryOutputMapPath,
      ).writeAsBytes([9, 8, 7], flush: true);

      await expectLater(
        gateway.promote(
          workspace: workspace,
          destinationPath: configuration.outputMapPath,
          replaceExisting: true,
        ),
        throwsA(isA<FileSystemException>()),
      );

      expect(moveCount, 3);
      expect(await File(configuration.outputMapPath).readAsBytes(), [4, 5, 6]);
      expect(
        await outputRoot
            .list()
            .where(
              (entity) =>
                  entity is File && entity.path.contains('.backup-eud-'),
            )
            .toList(),
        isEmpty,
      );
      await gateway.cleanup(workspace);
    });

    test('preserves the backup when automatic restoration fails', () async {
      var moveCount = 0;
      gateway = LocalEudBuildFileGateway(
        fileMover: (source, destinationPath) async {
          moveCount++;
          if (moveCount >= 2) {
            throw FileSystemException(
              'simulated move failure',
              destinationPath,
            );
          }
          await source.rename(destinationPath);
        },
      );
      final configuration = _configuration(
        baseMap: baseMap,
        sourceRoot: sourceRoot,
        entrySource: entrySource,
        outputRoot: outputRoot,
      );
      await File(
        configuration.outputMapPath,
      ).writeAsBytes([4, 5, 6], flush: true);
      final workspace = await gateway.createWorkspace(configuration);
      await File(
        workspace.temporaryOutputMapPath,
      ).writeAsBytes([9, 8, 7], flush: true);

      late EudBuildPromotionRecoveryException recoveryError;
      try {
        await gateway.promote(
          workspace: workspace,
          destinationPath: configuration.outputMapPath,
          replaceExisting: true,
        );
        fail('Expected promotion and restoration to fail.');
      } on EudBuildPromotionRecoveryException catch (error) {
        recoveryError = error;
      }

      expect(moveCount, 3);
      expect(await File(configuration.outputMapPath).exists(), isFalse);
      expect(await File(recoveryError.backupPath).readAsBytes(), [4, 5, 6]);
      await gateway.cleanup(workspace);
      expect(await File(recoveryError.backupPath).exists(), isTrue);
    });

    test('rejects missing or non-regular build inputs', () async {
      final missingEntry = File(
        '${sourceRoot.path}${Platform.pathSeparator}missing.eps',
      );
      final configuration = _configuration(
        baseMap: baseMap,
        sourceRoot: sourceRoot,
        entrySource: missingEntry,
        outputRoot: outputRoot,
      );

      await expectLater(
        gateway.validateInputs(configuration),
        throwsA(isA<FileSystemException>()),
      );
    });
  });
}

EudBuildConfiguration _configuration({
  required File baseMap,
  required Directory sourceRoot,
  required File entrySource,
  required Directory outputRoot,
  Map<String, String> compilerOptions = const {},
}) {
  return EudBuildConfiguration(
    baseMapPath: baseMap.absolute.path,
    sourceRootPath: sourceRoot.absolute.path,
    entrySourcePath: entrySource.absolute.path,
    outputMapPath:
        '${outputRoot.absolute.path}${Platform.pathSeparator}Generated.scx',
    compilerOptions: compilerOptions,
  );
}
