import 'dart:convert';
import 'dart:io';

// ARB is the sole source for the stable-ID resolver and legacy display adapter.
void main() {
  final arb =
      jsonDecode(File('lib/l10n/app_en.arb').readAsStringSync())
          as Map<String, dynamic>;
  final messages = <String, String>{
    for (final entry in arb.entries)
      if (entry.key.startsWith('editor') && entry.value is String)
        entry.key: entry.value as String,
  };
  final output = StringBuffer(
    '// Generated by dart run tool/generate_editor_messages.dart. Do not edit.\n'
    "part of 'editor_message_localization.dart';\n\n",
  );
  final placeholder = RegExp(r'\{value\d+\}');
  output.writeln(
    'String? resolveEditorMessage(AppLocalizations l10n, String? id, List<String> values) => switch (id) {',
  );
  for (final entry in messages.entries) {
    final count = placeholder.allMatches(entry.value).length;
    final guard = count == 0
        ? 'when values.isEmpty'
        : 'when values.length == $count';
    final args = count == 0
        ? ''
        : '(${List.generate(count, (i) => 'values[$i]').join(', ')})';
    output.writeln('  ${_quote(entry.key)} $guard => l10n.${entry.key}$args,');
  }
  output.writeln('  _ => null,\n};\n');
  output.writeln('const _exactMessages = <String, String>{');
  for (final entry in messages.entries) {
    if (!placeholder.hasMatch(entry.value)) {
      output.writeln('  ${_quote(entry.value)}: ${_quote(entry.key)},');
    }
  }
  output.writeln('};\n');
  final templates =
      messages.entries
          .where((entry) => placeholder.hasMatch(entry.value))
          .toList()
        ..sort(
          (a, b) => b.value
              .replaceAll(placeholder, '')
              .length
              .compareTo(a.value.replaceAll(placeholder, '').length),
        );
  output.writeln('final _legacyTemplates = <({RegExp pattern, String id})>[');
  for (final entry in templates) {
    final parts = entry.value.split(placeholder);
    final pattern = '^${parts.map(RegExp.escape).join('([\\s\\S]*?)')}\$';
    output.writeln(
      '  (pattern: RegExp(${_quote(pattern)}), id: ${_quote(entry.key)}),',
    );
  }
  output.writeln('];');
  File(
    'lib/presentation/localization/editor_messages.g.dart',
  ).writeAsStringSync(output.toString());
}

String _quote(String value) =>
    "'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\$', '\\\$').replaceAll('\n', '\\n').replaceAll('\r', '\\r')}'";
